import = ["~/.config/alacritty/themes/catppuccin_macchiato.toml"]

[window]
padding = { x = 12, y = 12 }
decorations = "None"
opacity = 0.8
blur = true

[font]
normal = { family = "SFMono Nerd Font", style = "Regular" }
bold = { family = "SFMono Nerd Font", style = "Medium" }
italic = { family = "SFMono Nerd Font", style = "Regular Italic" }
bold_italic = { family = "SFMono Nerd Font", style = "Medium Italic" }
offset = { x = 0, y = 2 }
size = 14.0

[scrolling]
history = 20000
multiplier = 1

[cursor]
style = { shape = "Block" }

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Super" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"


[keyboard]
bindings = [
  # Tmux forward keybinds
  { key = "D", mods = "Super", chars = "\u0001%" },
  { key = "D", mods = "Super | Shift", chars = "\u0001\"" },
  { key = "W", mods = "Super", chars = "\u0001x" },
  { key = "[", mods = "Super", chars = "\u0001[0" },
  { key = "Z", mods = "Super", chars = "\u0001z" },

  # Nvim forward keybinds
  { key = "T", mods = "Super", chars = "\u0001c" },
  { key = "1", mods = "Super", chars = "\u00011" },
  { key = "2", mods = "Super", chars = "\u00012" },
  { key = "3", mods = "Super", chars = "\u00013" },
  { key = "4", mods = "Super", chars = "\u00014" },
  { key = "5", mods = "Super", chars = "\u00015" },
  { key = "6", mods = "Super", chars = "\u00016" },
  { key = "7", mods = "Super", chars = "\u00017" },
  { key = "8", mods = "Super", chars = "\u00018" },
  { key = "9", mods = "Super", chars = "\u00019" },
  { key = "E", mods = "Super | Shift", chars = "\u001b[13~" },
  { key = "E", mods = "Super", chars = "\u001b[14~" },
  { key = "G", mods = "Super | Shift", chars = "\u0020\u0047" },
  { key = "G", mods = "Control | Shift", chars = "\u0020\u0047" },
  { key = "G", mods = "Super", chars = "\u0007" },
  { key = "P", mods = "Super", chars = "\u0010" },
  { key = "B", mods = "Super", chars = "\u0002" },
  { key = "S", mods = "Super", chars = "\u0013" },
  { key = "H", mods = "Super", chars = "\u0020\u0071\u0068" },
  { key = "J", mods = "Super", chars = "\u0020\u0071\u006A" },
  { key = "K", mods = "Super", chars = "\u0020\u0071\u006B" },
  { key = "L", mods = "Super", chars = "\u0020\u0071\u006C" },
  { key = "/", mods = "Super", chars = "\u0020\u0071\u002F" },
  { key = ".", mods = "Super", chars = "\u0020\u0071\u002E" },
  { key = "1", mods = "Control", chars = "\u0020\u0031" },
  { key = "2", mods = "Control", chars = "\u0020\u0032" },
  { key = "3", mods = "Control", chars = "\u0020\u0033" },
  { key = "4", mods = "Control", chars = "\u0020\u0034" },
  { key = "5", mods = "Control", chars = "\u0020\u0035" },

  # Unbind
  { key = "N", mods = "Super", action = "None" },
]
