gui:
  theme:
    activeBorderColor:
      - blue
      - bold
    # inactiveBorderColor:
    #   - black
  showFileTree: true # for rendering changes files in a tree format
os:
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
  editAtLineAndWait: "nvim +{{line}} {{filename}}"
  editInTerminal: true
keybinding:
  universal:
    quit: "q"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
