gui:
  theme:
    activeBorderColor:
      - blue
      - bold
    # inactiveBorderColor:
    #   - black
  showFileTree: true # for rendering changes files in a tree format
os:
  editPreset: "nvim"
  edit: "nvim"
  editAtLine: "{{editor}} {{filename}}"
keybinding:
  universal:
    quit: "q"
