local function bind_app(key, app_name)
	hs.hotkey.bind({ "alt" }, key, function()
		return hs.application.launchOrFocus(app_name)
	end)
end

bind_app("t", "Ghostty")
bind_app("x", "Finder")
bind_app("g", "Arc")
bind_app("m", "Spotify")
bind_app("s", "Slack")
bind_app("f", "Figma")
bind_app("c", "Rise")
bind_app("z", "zoom.us")
bind_app("d", "Tayasui Sketches")
bind_app("w", "WhatsApp")
bind_app("b", "Spark")
bind_app("v", "Proton Pass")
