#!/bin/bash

source "$CONFIG_DIR/colors.sh"

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

# sketchybar --bar position=top height=36 y_offset=8 margin=12 corner_radius=6 blur_radius=30 padding_left=2 padding_right=2 color=0x66494d64
sketchybar --bar position=top height=36 y_offset=8 margin=12 corner_radius=6 blur_radius=30 padding_left=2 padding_right=2 color=0x22000000

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=4
  padding_right=4
  icon.font="Hack Nerd Font:Bold:13.0"
  label.font="SF Pro:Semibold:13.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
  background.color=0x44ffffff
  background.corner_radius=4
  background.drawing=on
  background.border_color=0xAAFFFFFF
  background.border_width=0
  background.height=24
  updates=on
)
sketchybar --default "${default[@]}"

##### Adding aeropsace layouts #####

# Add the aerospace_workspace_change event we specified in aerospace.toml
sketchybar --add event aerospace_workspace_change

# This only works for single monitor configs!
for sid in $(aerospace list-workspaces --monitor 1); do
  #for sid in "${SPACE_IDS[@]}"; do
  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change \
    --set space.$sid \
    drawing=off \
    icon="$sid" \
    icon.padding_left=8 \
    label.font="sketchybar-app-font:Regular:16.0" \
    label.padding_right=16 \
    label.padding_left=0 \
    label.y_offset=-1 \
    click_script="aerospace workspace $sid" \
    script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

# Load Icons on startup
for sid in $(aerospace list-workspaces --monitor 1 --empty no); do
  apps=$(aerospace list-windows --workspace "$sid" | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')

  sketchybar --set space.$sid drawing=on icon.drawing=off

  icon_strip=" "
  if [ "${apps}" != "" ]; then
    while read -r app; do
      icon_strip+=" $($CONFIG_DIR/plugins/icon_map_fn.sh "$app")"
    done <<<"${apps}"
  else
    icon_strip=""
  fi
  sketchybar --set space.$sid label="$icon_strip"
done

# ---

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

# sketchybar --add item front_app_separator left \
#   --set front_app_separator icon.drawing=off label="->" \
#   --add item front_app left \
#   --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
#   --subscribe front_app front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
  --set clock update_freq=10 script="$PLUGIN_DIR/clock.sh" \
  icon.padding_right=0 \
  label.padding_left=0 \
  --subscribe volume volume_change

sketchybar --add item battery right \
  --set battery \
  update_freq=20 \
  icon.font="Hack Nerd Font:Bold:10.0" \
  script="$PLUGIN_DIR/battery.sh"

sketchybar -m --add item network_down right \
  --set network_down label.font="SF Pro:Heavy:10" \
  icon.font="SF Pro:Black:10" \
  icon=􀱈 \
  icon.highlight_color=0xff98ff98 \
  icon.y_offset=0 \
  icon.padding_right=4 \
  label.padding_left=0 \
  label.y_offset=0 \
  label.align=right \
  y_offset=0 \
  background.y_offset=0 \
  update_freq=2 \
  script="$PLUGIN_DIR/speed.sh" \
  \
  --add item network_up right \
  --set network_up label.font="SF Pro:Heavy:10" \
  icon.font="SF Pro:Black:10" \
  icon=􀄮 \
  icon.color=0xffffffff \
  icon.highlight_color=0xffffc0cb \
  icon.y_offset=0 \
  icon.padding_right=4 \
  label.padding_left=0 \
  label.y_offset=0 \
  label.align=right \
  y_offset=0 \
  background.y_offset=0

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
