#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"

sketchybar --bar \
  position=top \
  height=36 \
  y_offset=8 \
  margin=12 \
  corner_radius=6 \
  blur_radius=10 \
  padding_left=2 \
  padding_right=2 \
  color=$BACKGROUND_BAR \
  shadow=on

default=(
  padding_left=4
  padding_right=4
  # icon.font="Hack Nerd Font:Bold:13.0"
  icon.font="SF Pro:Bold:13.0"
  label.font="SF Pro:Bold:13.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_right=4
  background.color=$BACKGROUND_SURFACE
  background.corner_radius=4
  background.drawing=on
  background.border_color=0xAAFFFFFF
  background.border_width=0
  background.height=24
  updates=on
)
sketchybar --default "${default[@]}"

sketchybar --add event aerospace_workspace_change

sketchybar --add item front_app left \
  --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app front_app_switched

sketchybar --add item svim.mode left \
  --set svim.mode popup.align=left \
  icon= \
  icon.font="Hack Nerd Font Mono:Bold:20.0" \
  icon.padding_left=8 \
  icon.padding_right=8 \
  icon.color=$WHITE \
  label.font="Hack Nerd Font Mono:Bold:13.0" \
  label.drawing="off" \
  script="sketchybar --set svim.mode popup.drawing=off" \
  --subscribe svim.mode front_app_switched aerospace_workspace_change \
  --add item svim.cmdline popup.svim.mode \
  --set svim.cmdline icon="Command: "

# for sid in $(aerospace list-workspaces --monitor 1 --empty no); do
for sid in $(aerospace list-workspaces --monitor 1); do
  # apps=$(aerospace list-windows --workspace "$sid" | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')
  apps=$(aerospace list-windows --workspace "$sid")

  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change \
    --set space.$sid \
    icon.drawing=off \
    label.padding_left=8 \
    label.padding_right=8 \
    label=$sid \
    click_script="aerospace workspace $sid" \
    script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

sketchybar --add item clock right \
  --set clock update_freq=10 script="$PLUGIN_DIR/clock.sh"
# icon=􀐫

sketchybar --add item battery right \
  --set battery \
  update_freq=20 \
  drawing=off \
  script="$PLUGIN_DIR/battery.sh"

sketchybar -m --add item network_down right \
  --set network_down label.font="SF Pro:Heavy:10" \
  drawing=off \
  icon.font="SF Pro:Black:10" \
  icon=􀄩 \
  icon.highlight_color=$GREEN \
  icon.y_offset=0 \
  icon.padding_right=4 \
  label.padding_left=0 \
  label.y_offset=0 \
  label.align=right \
  y_offset=0 \
  background.y_offset=0 \
  update_freq=2 \
  script="$PLUGIN_DIR/speed.sh" \
  \
  --add item network_up right \
  --set network_up label.font="SF Pro:Heavy:10" \
  drawing=off \
  icon.font="SF Pro:Black:10" \
  icon=􀄨 \
  icon.color=0xffffffff \
  icon.highlight_color=$BLUE \
  icon.y_offset=0 \
  icon.padding_right=4 \
  label.padding_left=0 \
  label.y_offset=0 \
  label.align=right \
  y_offset=0 \
  background.y_offset=0

sketchybar --add item cpu right \
  --set cpu update_freq=4 \
  icon=􀫥 \
  script="$PLUGIN_DIR/cpu.sh"

sketchybar --add item ram right \
  --set ram update_freq=4 \
  icon=􀫦 \
  script="$PLUGIN_DIR/ram.sh"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
