# import = ["~/.config/alacritty/themes/catppuccin_mocha.toml"]
general.import = ["~/.config/alacritty/themes/poimandres.toml"]

[window]
padding = { x = 12, y = 12 }
decorations = "buttonless"
opacity = 0.8
blur = true
option_as_alt = "Both"

[font]
# normal = { family = "SFMono Nerd Font", style = "Regular" }
normal = { family = "SFMono Nerd Font", style = "Regular" }
bold = { family = "SFMono Nerd Font", style = "Medium" }
italic = { family = "SFMono Nerd Font", style = "Regular Italic" }
bold_italic = { family = "SFMono Nerd Font", style = "Medium Italic" }
offset = { x = -1, y = 2 }
size = 14.0

[scrolling]
history = 20000
multiplier = 1

[cursor]
style = { shape = "Block" }

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Super" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"


[keyboard]
bindings = [
  # Tmux forward keybinds
  # { key = "[", mods = "Control", chars = "\u0001[0" },
  # { key = "S", mods = "Control", chars = "\u0001s" },
  { key = "D", mods = "Control", chars = "\u0001%" },
  { key = "D", mods = "Control | Shift", chars = "\u0001\"" },
  { key = "W", mods = "Control", chars = "\u0001x" },
  { key = "S", mods = "Control", chars = "\u0001[0" },
  { key = "F", mods = "Control", chars = "\u0001z" },
  { key = "T", mods = "Control", chars = "\u0001c" },
  { key = "1", mods = "Super", chars = "\u00011" },
  { key = "2", mods = "Super", chars = "\u00012" },
  { key = "3", mods = "Super", chars = "\u00013" },
  { key = "4", mods = "Super", chars = "\u00014" },
  { key = "5", mods = "Super", chars = "\u00015" },
  { key = "6", mods = "Super", chars = "\u00016" },
  { key = "7", mods = "Super", chars = "\u00017" },
  { key = "8", mods = "Super", chars = "\u00018" },
  { key = "9", mods = "Super", chars = "\u00019" },

  # Tmux session quickswitch indexed at 0 by default
  { key = "1", mods = "Control", chars = "\u0001s1" },
  { key = "2", mods = "Control", chars = "\u0001s2" },
  { key = "3", mods = "Control", chars = "\u0001s3" },
  { key = "4", mods = "Control", chars = "\u0001s4" },
  { key = "5", mods = "Control", chars = "\u0001s5" },
  { key = "6", mods = "Control", chars = "\u0001s6" },
  { key = "7", mods = "Control", chars = "\u0001s7" },
  { key = "8", mods = "Control", chars = "\u0001s8" },
  { key = "9", mods = "Control", chars = "\u0001s9" },
  { key = "0", mods = "Control", chars = "\u0001s0" },

  # Nvim forward keybinds (\u0020\u0071\u0070 => space+q+p)
  # { key = "E", mods = "Super | Shift", chars = "\u0020\u0071\u0068" },
  # { key = "E", mods = "Super", chars = "\u0020\u0071\u006C" },
  # { key = "G", mods = "Super | Shift", chars = "\u0020\u0047" },
  # { key = "P", mods = "Super", chars = "\u0020\u0071\u0070" },
  # { key = "B", mods = "Super", chars = "\u0020\u0071\u0062" },
  # { key = "S", mods = "Super", chars = "\u0020\u0071\u0073" },
  # { key = "G", mods = "Super", chars = "\u0020\u0071\u0067" },
  # { key = "H", mods = "Super", chars = "\u0020\u0071\u0068" },
  # { key = "W", mods = "Super", chars = "\u0020\u0071\u0077" },
  # { key = "D", mods = "Super", chars = "\u0020\u0071\u0064" },
  # { key = "D", mods = "Super | Shift", chars = "\u0020\u0071\u0044" },
  # { key = "J", mods = "Super", chars = "\u0020\u0071\u006A" },
  # { key = "K", mods = "Super", chars = "\u0020\u0071\u006B" },
  # { key = "L", mods = "Super", chars = "\u0020\u0071\u006C" },
  # { key = "/", mods = "Super", chars = "\u0020\u0071\u002F" },
  # { key = ".", mods = "Super", chars = "\u0020\u0071\u002E" },

  # Unbind
  # { key = "N", mods = "Super", action = "None" },
  # { key = "T", mods = "Super", action = "None" },
]
