"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 3

# Path
[[blocks]]
type = "prompt"
alignment = "left"
newline = true
[[blocks.segments]]
type = "path"
style = "plain"
foreground = "p:blue"
background = "transparent"
template = "{{ .Path }}"
[blocks.segments.properties]
style = "folder"

[[blocks.segments]]
type = 'git'
style = 'plain'
foreground = 'p:grey'
background = 'transparent'
# template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
# template = ' {{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</> <green>{{ if gt .Added	0 }} {{ end }}</> <red>{{ if gt .Deleted	0 }} {{ end }}</>'
# template = ' {{ if .Working.Changed }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣ {{ end }}{{ if gt .Ahead 0 }}⇡ {{ end }}</><magenta>{{ if .Working.Changed  }} sa {{ .Working.Added }} {{ end }} {{ if .Working.Changed  }} ss {{ .Working.String }} {{ end }} {{ if .Staging.Changed  }} sa {{ .Staging.Added }} {{ end }} {{ if .Staging.Changed  }} ss {{ .Staging.String }} {{ end }}</><magenta>{{ if gt .StashCount 0}}  {{ .StashCount }} {{ end }}</>'

# template: '{{ .HEAD }} {{ .BranchStatus }}{{ if .Working.Changed }} \uF044 {{ .Working.String }}{{ end }}{{ if and (.Staging.Changed) (.Working.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uF046 {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0}} \uF692 {{ .StashCount }}{{ end }}{{ if gt .WorktreeCount 0}} \uf1bb {{ .WorktreeCount }}{{ end }}'
# [blocks.segments.properties]
# branch_icon = ''
# commit_icon = '@'
# branch_ahead_icon = '⇡'
# branch_behind_icon = '⇣'
# branch_gone_icon = '?'
# branch_identical_icon = ''
# cherry_pick_icon = 'pick'
# revert_icon = '↩'
# rebase_icon = 'rb'
# merge_icon = 'M'
# fetch_status = true


# Exec time
[[blocks]]
type = 'rprompt'
overflow = 'hidden'
[[blocks.segments]]
type = 'executiontime'
style = 'plain'
foreground = 'yellow'
background = 'transparent'
template = '{{ .FormattedMs }}'
[blocks.segments.properties]
threshold = 5000

# Pre prompt
[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true
[[blocks.segments]]
type = 'text'
style = 'plain'
foreground_templates = [
  "{{if gt .Code 0}}red{{end}}",
  "{{if eq .Code 0}}green{{end}}",
]
background = 'transparent'
template = '~>'

[transient_prompt]
foreground_templates = [
  "{{if gt .Code 0}}red{{end}}",
  "{{if eq .Code 0}}green{{end}}",
]
background = 'transparent'
template = '~> '

[palette]
black = "#1b1e28"
red = "#d0679d"
green = "#5de4c7"
yellow = "#fffac2"
blue = "#89ddff"
magenta = "#fcc5e9"
cyan = "#add7ff"
white = "#ffffff"
